name: xgems

channels:
  - conda-forge

dependencies:
  - pip
  - gxx_linux-64 # [linux]
  - cmake>=3.16
  - ninja
  - git
  - ccache  # [unix]
  - pybind11
  - python>=3.10
  - pytest
  - nlohmann_json
  - numpy
  - eigen>=3.4.0
  - gems3k=>4.4.3
 
